version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: mydatabase         
      MYSQL_USER: myuser                 
      MYSQL_PASSWORD: mypassword         
    volumes:
      - mysql_data:/var/lib/mysql        
    ports:
      - "3306:3306"                      

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db                       
      PMA_PORT: 3306                     
      PMA_ARBITRARY: 0                   
    ports:
      - "8080:80"                        
    depends_on:
      - db                               

volumes:
  mysql_data: